# Generated by Django 3.2.14 on 2022-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servinquilino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('dni', models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='DNI')),
                ('pasword', models.CharField(max_length=10, verbose_name='Pasword')),
            ],
        ),
    ]
