# Generated by Django 3.2.14 on 2022-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servinquilino', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='DNI'),
        ),
    ]
